# SENSOR TYPES
SENSOR_MOTION = 1
SENSOR_TEMPERATURE = 2
SENSOR_HUMIDITY = 3
SENSOR_LOUD_SOUND = 4
SENSOR_WEATHER = 5
SENSOR_BINARY_SENSOR = 6
SENSOR_BINARY_SWITCH = 7
SENSOR_VIDEO = 8
SENSOR_SIREN = 9
SENSOR_AUDIO = 10
SENSOR_AMBIENT_LIGHT = 11
SENSOR_TIME = 12
SENSOR_UNKNOWN = 13
SENSOR_REPEATER = 14
SENSOR_MULTILEVEL_SWITCH = 15
SENSOR_ORIENTATION = 16
SENSOR_PANIC = 17
SENSOR_THERMOSTAT = 18

# Sensors appear in rule page as trigger
triggerable_sensor_types = (
    SENSOR_BINARY_SENSOR,
    #SENSOR_MOTION,
    SENSOR_AMBIENT_LIGHT,
    SENSOR_LOUD_SOUND,
    SENSOR_TEMPERATURE,
    SENSOR_TIME
)
# Sensors appear in automation page
automatable_sensor_types = (
    SENSOR_BINARY_SWITCH,
    SENSOR_MULTILEVEL_SWITCH,
    SENSOR_THERMOSTAT
)
